### PR TITLE
Composer v2 compatibility

### PR DESCRIPTION
**Pull request by thojou**
Hi,

Today I encountered an issue with composer v2, which has been already reported in #106. 
Here is the PR that should fix this issue.

I'm not sure, how to handle the new introduced `installed-path` inside a package definition. May that be a replacement for `target-dir`. If you think so, I can update this part as well.

What is your thought on the new PHPUnit-Test? Currently, it is duplicated code from `testBundlePackageWithNoVendorReturnsEmptyBundle`. Should we use a dataProvider instead?

### CODE REVIEW

**Review by nargotik — CHANGES_REQUESTED** [review]
The solution could be only this line, not needing to pass an entire array to another method verify the same array.
```php
$installed = empty($installed['packages']) ? $installed : $installed['packages'];
```

**Comment by soyuka** [comment]
:+1:

**Comment by nargotik** [comment]
> change works +1
> 
> ```
> $installed = $installed['packages'] ?? $installed;
> ```

Yes but this would make incompatible with php5.3 i think

**Comment by wimleers** [comment]
> Yes but this would make incompatible with php5.3 i think

Which is probably why most builds are failing.

Could the PR be updated to use syntax that is more backwards compatible? 🙏 😊

**Comment by nargotik** [comment]
@wimleers the PR is already backwards  even using this aproach or aproach on #108 that I have already closed due duplication of issues solved.

**Comment by clue** [comment]
@thojou Thanks for looking into this and providing this high-quality PR with some additional tests!

I've just applied your changes with #114 after introducing some additional test changes now that #112 is in.

Now let's get this shipped! :shipit: 

Keep it up!

**Pull request closed without merging**
