### PR TITLE
Validate composer.json when composer binary is available

### LINKED ISSUE #43: validate composer.json
phar-composer commands assume the composer.json provided is valid.

In case it is not valid it sometimes produces strange things, e.g. name a project "myproject" (without a vendor prefix, which of course is invalid).
-> it will create a "yproject.phar" (without the leading "m"). It took some time to find out, that this problems are caused by my invalid composer.json.

phar-composer could do a better job and do a `composer validate` before each runs its own commands. In case of errors, skip its own command and print the error.

### PR DESCRIPTION
**Pull request by staabm**
fixes #43

### CODE REVIEW

**Comment by staabm** [comment]
@clue hacked something together. hadn't time yet to test it so take it with a grain of salt.

**Comment by clue** [comment]
Thanks for the PR! I like the concept and would love to get this in!

Some tests and documentation would be much appreciated.
I'll review this in more detail soon.

The CI setup is currently broken (see #49), so I'll have to postpone this for now.

**Comment by staabm** [comment]
@clue added docs (changelog infos, not sure if you meant to promote the feature elsewhere. If so just tell me) and tests.

**Comment by clue** [comment]
Thanks for the update @staabm, LGTM :+1: I'll postpone this for now and am looking into getting this into the next release.

**Comment by staabm** [comment]
@clue ping

**Comment by staabm** [comment]
Ping

**Comment by staabm** [comment]
Ping

**Comment by hopeseekr** [comment]
There never was a next release. :-(

Well, the good news is that after exactly 4 years and 20 days, I have merged this PR into my new fork of phar-composer. I will be releasing it shortly.

**Comment by clue** [comment]
@staabm Thank you for filing this PR and for your patience! I very much value your contribution and I think this would have deserved a review much earlier, but I'm having to close this PR as per https://github.com/clue/phar-composer/issues/43#issuecomment-551449580. Again, thank you for your contribution and keep it up :+1:

**Pull request closed without merging**
