### PR TITLE
Switch to error message instead of info

### PR DESCRIPTION
**Pull request by Nek-**
Just a little contribution but I was pretty confused when I saw the green message saying « there is an error ».

So here is a fix to write it properly.

### CODE REVIEW

**Comment by clue** [comment]
Thanks for the PR, but the motivation is a bit unclear to me, perhaps you can elaborate? :+1: 

The message is in fact only there to inform the user, this is not a fatal error.

**Comment by Nek-** [comment]
This error pop over when the phar extension is missing. Which is a critical issue isn't it ? But well, maybe I modified the wrong message, sorry :o .

**Comment by clue** [comment]
I have yet to confirm this, but IIRC this should only be invoked if the `phar.readonly` setting is enabled.

Can you confirm either observation?

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:

**Pull request closed without merging**
