### PR TITLE
Modernize CI config, add PHP 7.4

### PR DESCRIPTION
**Pull request by szepeviktor**
Please consider migrating to travis-ci.com

### CODE REVIEW

**Comment by szepeviktor** [comment]
https://github.com/clue/phar-composer/blob/master/tests/Phar/PackagerTest.php#L125

`/home/me` does not exist in CI.
What to do now?

**Comment by SimonFrings** [comment]
Thanks for looking into this :+1: 
We're currently moving away from travis towards github actions.
Take a look at actions/toolkit#112.

**Comment by szepeviktor** [comment]
All right.
Hype over maturity.

**Comment by clue** [comment]
@szepeviktor Thanks for looking into this and filing this PR! I think we all agree modernizing was indeed long overdue, so we've applied the relevant changes with actions/toolkit#112 after some careful considerations. Keep it up :+1:

**Comment by szepeviktor** [comment]
You know while developing my first GHA action already published on Marketplace I've realized GHA it not yet fit for advanced usage.
So I say Travis CI.

**Comment by clue** [comment]
@szepeviktor Rest assured we have plenty of knowledge with Travis CI, GitHub actions and a variety of other CI systems and build tools. Travis has served us well for around 7 years, but after its recent acquisition and changes in its pricing model, it's time for us to move on. GitHub actions may not be perfect, but we haven't encountered any serious issues in the last months of using it for a number of different workflows, so it's definitely capable of replacing our existing CI system. Thanks for your consideration.

If you feel there's anything that can be improved with our new CI setup, feel free to file a PR to improve upon actions/toolkit#112 and I'm happy to take a look :+1:

**Comment by szepeviktor** [comment]
I want to do advanced things with a computer/CI and I cannot with GHA 😿

**Comment by clue** [comment]
> I want to do advanced things with a computer/CI and I cannot with GHA crying_cat_face

Don't worry, we're here to help.

I'm not sure I follow what you're after. Please create a dedicated issue to discuss what "advanced things" could be missing for this project.

**Comment by szepeviktor** [comment]
> I'm not sure I follow what you're after. Please create a dedicated issue to discuss what "advanced things" could be missing for this project.

There is no issue with phar-composer or its GHA workflows.

Generally GHA is no-go for viktor as it lacks mature features, e.g. https://github.com/actions/runner/issues/2347
Another example is to access the value of `$HOME` which is not possible.
Please do not make me list all shortcomings... it makes me angry as I've spent a lot of time investigating those.

**Comment by clue** [comment]
> Please do not make me list all shortcomings... it makes me angry as I've spent a lot of time investigating those.

@szepeviktor No need to be angry, you can keep using whatever CI you're most comfortable with for your projects :+1: 

For **this** particular project we've evaluated GitHub actions to be suitable and we're not affected by any issues.

**Pull request closed without merging**
