### PR TITLE
Fix test visibility failure with newer phpunit versions

### PR DESCRIPTION
**Pull request by schorsch3000**
Hi,
i've tried to build a phar-composer.phar from source, but got stuck while running tests:
phpunit at least in v5.5.0 requires createMock() to be protected or public, at the moment it is private.
That will result in errors while testing.

These changes don't effect production code nor the test results.

This should be a quick-merger :)

Thanks so long for your effort!

### CODE REVIEW

**Comment by schorsch3000** [comment]
hmm, that's odd.
i'm able to run all tests:

`PHPUnit 5.5.0 by Sebastian Bergmann and contributors.

.............................W...                                 33 / 33 (100%)

Time: 193 ms, Memory: 6.00MB

There was 1 warning:

1) TargetPharTest::buildFromIteratorProvidesBasePathForBox
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead

WARNINGS!
Tests: 33, Assertions: 52, Warnings: 1.
`
on that exactly commit...

using php7.0.9 and php5.6.23

any idea whats going on?

**Comment by clue** [comment]
Thanks for filing this PR :+1: Can you look into the other failing tests?

**Comment by schorsch3000** [comment]
The tests don't fail in my setup.
I could try to mimic the Travis setup.
I'll think I have a go this weekend about this.
I have the feeling that it's a problem with old vs. new versions of
phpunit. Would an updated setup be a solution to you?

Am 18.08.2016 7:04 nachm. schrieb "Christian Lück" <notifications@github.com

**Comment by clue** [comment]
Thanks for digging into this @schorsch3000! I prefer smaller changesets as this will help with reviewing this, other than that I'm fine with updating literally everything :+1:

**Comment by schorsch3000** [comment]
This seems to be a race-condition type of error, on my machine running phpunit in a loop along with  `git reset --hard `  fails in about one in 20 to 25 runs.

setting all cores on fire with endless loops doing nothing then looping i'll get an error about every 3rd test run.

As the travis server are on fire all the time, that explains why it fails always there.

Any idea about a possible root cause of a race condition?

I think Packager::exec() might be a good starting point, any other hints from you maybe?

i'll investigate on this later this weekend.

**Comment by schorsch3000** [comment]
there you go: https://travis-ci.org/schorsch3000/phar-composer/jobs/153626078 https://travis-ci.org/schorsch3000/phar-composer/builds/153625522

Only difference between these two builds: removed php5.3 test box since it's EOL for about 2 years and i removed the script command:   `-  echo "<?php phpinfo();" | php | grep phar` which was in there just to see if travis is configured as my box.

Now i'll have to hunt dows that little race condition :(

**Comment by schorsch3000** [comment]
i'm sorry, i've spend a few hours to hunt this nasty race condition, i'll give up :(

**Pull request closed without merging**
